Sprint0/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'index' => 'welcome#index'
  get 'requests/form'
  get 'requests/index'
  get 'welcome/homepage'
  
  
  
resources :requests 
resources :applications
resources :charges

  
  devise_scope :user do
  root :to => 'devise/sessions#new'
  end
   

end

Sprint0/app/models/application.rb
class Application < ActiveRecord::Base
    
   def self.search(query)
   where("appname like ?", "%#{query}%") 
   end
    
    
end

Sprint0/app/models/request.rb
class Request < ActiveRecord::Base
end

Sprint0/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

Sprint0/app/controllers/account_controller.rb
class AccountController < ApplicationController
    def signin
        
    end
    
    
end

Sprint0/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
  welcome_homepage_path
  end
  
  def after_sign_up_path_for(resource)
  welcome_homepage_path
  end
  
  
  
  
end

Sprint0/app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
    
    
    def new 
    end
    
   def index
   if params[:search]
    @applications = Application.search(params[:search]).order("created_at DESC")
    end
  end
  # It returns the articles whose titles contain one or more words that form the query

    
    
    def show
    @application = Application.find(params[:id])
    end
    def create 
        @application = Application.new(application_params)
        @application.save
        
        @application.publisher_email  = current_user.email
        @application.save
        redirect_to @application
    end
    
    private
     def application_params
    params.require(:application).permit(:appname, :description, :price)
     end
end
    
    

Sprint0/app/controllers/charges_controller.rb
    
    
    class ChargesController < ApplicationController
    
    
    def new
    end

def create
  # Amount in cents
    @amount = params[:number]   

  customer = Stripe::Customer.create(
    :email => 'example@stripe.com',
    :card  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      =>  @amount ,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to charges_path(params[:number],params[:application])
end
end

Sprint0/app/controllers/requests_controller.rb
class RequestsController < ApplicationController
    
    
     def index
        @requests=Request.all
    end
    
    def show
        @request=Request.find(params[:id])
    end
    
    def new
    @request = Request.new
    end
   
    def create
    @request = Request.new(requests_params)
    @request.save
    end
   
  
  def destroy
      
   @request = Request.find(params[:id])
   @request.destroy
   @request.save
   if  params[:number] == "1"
   current_user.publisher = true
   @current_user.save
   end
   redirect_to requests_path
   
  end

  private
  def requests_params
    params.require(:request).permit(:reason, :user_email)
  end
 
end

Sprint0/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
   
  
  def homepage
  end
  
   def index
   end
    
  
end

Sprint0/app/helpers/account_helper.rb
module AccountHelper
end

Sprint0/app/helpers/application_helper.rb
module ApplicationHelper
end

Sprint0/app/helpers/applications_helper.rb
module ApplicationsHelper
end

Sprint0/app/helpers/charges_helper.rb
module ChargesHelper
end

Sprint0/app/helpers/requests_helper.rb
module RequestsHelper
end

Sprint0/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Sprint0/app/views/applications/index.html.erb
<table>
  <tr>
    <th>Appname</th>
    <th>Price</th>
     <th>Description</th>
    <th colspan="3"></th>
  </tr>
 
  <% @applications.each do |application| %>
    <tr>
      <td><%= application.appname %></td>
      <td><%= application.price %></td>
      <td><%= application.description %></td>
      <td><%= link_to 'Show' , application_path(application) %></td>
     </tr>
  <%end%>
</table>

Sprint0/app/views/applications/new.html.erb
<h1>New Application</h1>
<%= form_for :application, url: applications_path do |f| %>
  <p>
    <%= f.label :appname %><br>
    <%= f.text_field :appname %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  
    <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

Sprint0/app/views/applications/show.html.erb
<p>
  <strong>appname:</strong>
  <%= @application.appname %>
</p>
 
<p>
  <strong>description:</strong>
  <%= @application.description %>
</p>

<p>
  <strong>price: $</strong>
  <%=  @application.price %>

<p>
  
<% @number =  @application.price * 100 %>

<%= form_tag charges_path(:number => @number ,:application => @application) do %>


  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Payment"
          data-amount= <%= @application.price * 100 =%> </script> ></script>
<% end %>

Sprint0/app/views/requests/form.html.erb
<h1>Request</h1>
<%= form_for :request, url: requests_path do |f| %>
  
 
  <p>
    <%= f.label :reason %><br>
    <%= f.text_area :reason %>
    <%= f.text_area :user_email, :value => current_user.email %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

<% end %>

Sprint0/app/views/requests/index.html.erb
<h1> Requests </h1>
 
<table>
  <tr>
    <th>Request ID</th>
    <th>User Email</th>
  </tr>
 
  <% @requests.each do |request| %>
    <tr>
      <td><%= request.id %></td>
      <td><%= request.user_email %></td>
       <td><%= link_to 'Show' , request_path(request) %></td>
      
              <td><%= link_to 'Accept', request_path(request, :number => "1"),
              method: :delete %></td>
      <td><%= link_to 'Reject', request_path(request, :number => "0"),
              method: :delete %></td>
       
       
  
    </tr>
  
   <% end %>
</table>

Sprint0/app/views/requests/new.html.erb
<h1>Request</h1>
<%= form_for :request, url: requests_path do |f| %>
  
 
  <p>
    <%= f.label :reason %><br>
    <%= f.text_area :reason %>
    <%= f.text_area :user_email, :value => current_user.email %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

<% end %>

Sprint0/app/views/requests/show.html.erb
<p>
  <strong>User Email:</strong>
  <%= @request.user_email %>
</p>
 
<p>
  <strong>Reason:</strong>
  <%= @request.reason %>
  
  
</p>

<%= link_to 'Back', requests_path(request)%>