Updated/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  get 'welcome/index'

  resources :articles do
  resources :comments
end
  root 'welcome#index'

end

Updated/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

Updated/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
end

Updated/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  
  # http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

Updated/app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

Updated/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count"></div>     
     <div id="fb-root"></div>
  <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>    

<script src="https://apis.google.com/js/plusone.js"></script>
<g:plus action="share" annotation="bubble"></g:plus>
 
<h2>Comments : </h2>
<%= render @article.comments %>
 
<p>Add a comment:</p>

<%= render 'comments/form' %>


 <% if current_user.try(:admin?) %>
<%= link_to 'Edit Article', edit_article_path(@article) %> 
<%end%>|
<%= link_to 'Back to Articles', articles_path %>

Updated/app/views/comments/_comment.html.erb
<p>
  <%= current_user.email %>
  :
  <%= comment.body %>
 </p> 
 <!-- <%= comment.commenter %> 


<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p> 
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p> -->

Updated/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Approved</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
    <div id= "user_nav" %>
        
        <% if user_signed_in? %>
        Sign in as <%= current_user.email %>.Not You ?
       <%= link_to "Sign Out",destroy_user_session_path, :method => :delete %>
       <% else %>
        <%= link_to "Sign Up",new_user_registration_path %> or  <%= link_to "Sign In",new_user_session_path %>
        <% end %>
        </div>
<% flash.each do |name,msg| %>
<%= content_tag :div ,msg, :d => "flash_#(name)" %>
 <% end %>


<%= yield %>

</body>
</html>

Updated/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<%= link_to 'My Blog', controller: 'articles' %>